project:
  type: website

website:
  title: "Chipmunk Pixel"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/chipmunk-pixel/

format:
  html:
    theme:
      light: simplex
      dark: solar
    css: styles.css



