project:
  type: website
  output-dir: docs
  resources: 
    - "posts/suno-bark/podcast.mp3"

website:
  title: "Pixies"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/8bit-pixies/

format:
  html:
    theme:
      light: simplex
      dark: solar
    css: styles.css



